config/routes.rb
Rails.application.routes.draw do
  root 'pages#show', page: 'home'
  get '/pages/:page', to: 'pages#show'
  resources :users, only: [:new, :create, :destroy]
  resources :tacospots, shallow: true

  resources :sessions, only: [:new, :create, :destroy]
  get '/login', to: 'sessions#new'
  get '/logout', to: 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/tacospot.rb
class Tacospot < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :tacospots

  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

private

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to login_path, alert: "Not authorized - you must be logged in!" if current_user.nil?
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new
    @tacospots = Tacospot.all
  end

  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      session[:tacospot_id] = @comment.id
      redirect_to tacospot_path
    else
      render :new
    end
  end

  def show
    @tacospot = Tacospot.find(params[:id])
    @comment = Comment.new
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update_attributes(comment_params)
      redirect_to tacospot_path
    else
      render :edit
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy
    redirect_to tacospot_path
  end

private

  def set_comment
    @comment = Comment.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:content, :image_url, :favorite_taco, :comment_id)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def show
    page = params[:page]
    render "pages/#{page}"
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to tacospots_path, notice: "You're in, welcome."
    else
      flash.now.alert = "Something went wrong. Try again."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "See you next time."
  end

end

app/controllers/tacospots_controller.rb
class TacospotsController < ApplicationController
  before_action :set_tacospot, only: [:show, :edit, :update, :destroy]
  before_action :authorize, except: [:index, :show]

  def new
    @tacospot = Tacospot.new
  end

  def index
    @tacospots = Tacospot.all
    @users = User.all
  end

  def show
    @tacospot = set_tacospot
  end

  def create
    @tacospot = Tacospot.new(tacospot_params)
    @tacospot.user_id = current_user.id
    if @tacospot.save
      flash[:notice] = "New Taco Spot!"
      redirect_to tacospots_path
    else
      render :new
    end
  end

  def edit
    @tacospot = set_tacospot
  end

  def update
    @tacospot = set_tacospot
    if @tacospot.update_attributes(tacospot_params)
      redirect_to tacospot_path
    else
      render :edit
    end
  end

  def destroy
    @tacospot = set_tacospot
    @tacospot.destroy
    redirect_to tacospots_path
  end

private

  def set_tacospot
    @tacospot = Tacospot.find(params[:id])
  end

  def tacospot_params
    params.require(:tacospot).permit(:name, :street_address, :city, :state, :zip, :hours, :cash_only, :image_url, :user_id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def index
    @user = User.all
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Welcome, you are in."
      redirect_to tacospots_path
    else
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end

private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tacospots_helper.rb
module TacospotsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taco Finder LA</title>
    <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Fresca" %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag "/taco-icon.ico" %>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <header>
      <div class="navbar-fixed">
        <nav>
          <div class="nav-wrapper">
            <ul class="left hide-on-small-and-down">
              <li><%= link_to root_path do %>
                 <%= image_tag "/taco-nav.png" %>
              <% end %></li>
            </ul>
            <li class="brand-logo center"><%= link_to "Taco Finder", tacospots_path %></li>
            <ul class="right hide-on-small-and-down">
              <li><% if current_user %>
                    Welcome, <%= current_user.name %>
                  <% end %></li>
              <li><% if current_user %>
                    <%= link_to "Log out", session_path("dummy"), method: :delete %>
                  <% end %></li>
              <li><% if current_user == nil %>
                    <%= link_to "Enter Taco Finder", login_path %>
                  <% end %></li>
              <li><% if current_user == nil %>
                    <%= link_to "Join Taco Finder", new_user_path %>
                  <% end %></li>
            </ul>
          </div>
        </nav>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
    <br>
    <br>
    <br>
    <br>
    <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
    <script type="text/javascript" src="app/assets/javascripts/materialize.min.js"></script>
  </body>
</html>

app/views/pages/home.html.erb
<h3>Let's Taco 'bout It...</h3>
<div class="row">
  <div class="col s10 m6">
    <div class="z-depth-0" class="card">
      <div class="z-depth-0" class="card-image">
        <img src="http://i.imgur.com/27Oqt6K.gif">
      </div>
      <div class="card-content">
        <p>Do you like tacos? Are you in (or near) Los Angeles? Great!
          This is a site dedicated to finding the best tacos for you.
          <%= link_to "Take a look around", tacospots_path %>, find a taco spot, and then get going.</p>
      </div>
      <div class="z-depth-0" class="card-action">
        <% if current_user %><%= link_to "Tell us about a new taco spot.", new_tacospot_path %><% end %><br>
        <% if current_user == nil %><%= link_to "Join to share your favorite taco spots.", new_user_path %><% end %><br>
        <% if current_user == nil %><%= link_to "Already joined? Log in!", login_path %><% end %>
      </div>
    </div>
  </div>
</div>
<br>
<br>
<br>
<br>

app/views/tacospots/create.html.erb
<h1>Tacospots#create</h1>
<p>Find me in app/views/tacospots/create.html.erb</p>

app/views/tacospots/destroy.html.erb
<h1>Tacospots#destroy</h1>
<p>Find me in app/views/tacospots/destroy.html.erb</p>

app/views/tacospots/edit.html.erb
<h2>Fix up a taco spot</h2>

<%= form_for @tacospot do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %><br>

  <%= f.label :street_address %>
  <%= f.text_field :street_address %><br>

  <%= f.label :city %>
  <%= f.text_field :city %><br>

  <%= f.label :state %>
  <%= f.text_field :state %><br>

  <%= f.label :zip %>
  <%= f.number_field :zip %><br>

  <%= f.label :hours %>
  <%= f.text_field :hours %><br>

  <%= f.label :cash_only %>
  <%= f.text_field :cash_only %><br>

  <%= f.label :image_url %>
  <%= f.text_field :image_url %><br>

  <%= f.submit "Fix this taco spot!" %>

<% end %>
<br>
<%= link_to "Just kidding, this taco spot is all good.", tacospots_path %>
<br>
<br>
<br>
<br>

app/views/tacospots/index.html.erb
<h2>Look at all these tacos!</h2>

<% @tacospots.each do |tacospot| %>

<h3><%= link_to tacospot.name, tacospot_path(tacospot) %></h3>
  <div class="row">
    <div class="col s9 m5">
      <div class="card">
        <div class="card-image">
          <%= image_tag tacospot.image_url %>
        </div>
        <div class="card-content">
          <p><%= tacospot.street_address %></p>
          <p><%= tacospot.city %>, <%= tacospot.state %>&nbsp;<%= tacospot.zip %></p>
          <p>Hours: <%= tacospot.hours %></p>
          <p>Cash only: <%= tacospot.cash_only %></p>
        </div>
      </div>
    </div>
  </div>
<br>
<% end %>
<br>
<br>
<br>
<br>

app/views/tacospots/new.html.erb
<h2>Add a new taco spot!</h2>

<%= form_for @tacospot do |f| %>

   <%= f.label :name %>
   <%= f.text_field :name %><br>

   <%= f.label :street_address %>
   <%= f.text_field :street_address %><br>

   <%= f.label :city %>
   <%= f.text_field :city %><br>

   <%= f.label :state %>
   <%= f.text_field :state %><br>

   <%= f.label :zip %>
   <%= f.number_field :zip %><br>

   <%= f.label :hours %>
   <%= f.text_field :hours %><br>

   <%= f.label :cash_only %>
   <%= f.text_field :cash_only %><br>

   <%= f.label :image_url %>
   <%= f.text_field :image_url %><br>

   <%= f.submit "Add taco spot!" %>

<% end %>
<br>
<p><%= link_to "Nah, changed my mind, take me back.", tacospots_path %></p>
<br>
<br>
<br>
<br>

app/views/tacospots/show.html.erb
<h2><%= @tacospot.name %></h2>

<div class="row">
  <div class="col s12 m6">
    <div class="card">
      <div class="card-image">
        <%= image_tag @tacospot.image_url %>
      </div>
      <div class="card-content">
        <p><%= @tacospot.street_address %></p>
        <p><%= @tacospot.city %>, <%= @tacospot.state %>&nbsp;<%= @tacospot.zip %></p>
        <p>Hours: <%= @tacospot.hours %></p>
        <p>Cash only: <%= @tacospot.cash_only %></p>
      </div>
      <div class="card-action">
        <p><%= link_to "Fix up this taco spot", edit_tacospot_path(@tacospot) if current_user %></p>
        <p><%= link_to "This taco spot no longer exists", tacospot_path, method: :delete, data: { confirm: "Are you sure?" } if current_user %></p>
      </div>
    </div>
  </div>
</div>
<br>
<br>
<br>
<br>

app/views/tacospots/update.html.erb
<h1>Tacospots#update</h1>
<p>Find me in app/views/tacospots/update.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/index.html.erb
<h1>User Index - Home for now</h1>

<div>about</div>
<div>random taco spot</div>
<div>search field</div>
<br>
<br>
<br>
<br>

app/views/users/new.html.erb
<h2>Care to join?</h2>
  <%= form_for @user do |f| %>
    <% if @user.errors.any? %>
      <div class="error_messages">
        <h2>How did you mess this up?</h2>
        <ul>
          <% for message in @user.errors.full_messages %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>
<br>
<br>
<br>
<br>